#!/usr/bin/env python3
"""Locate the first nonfinite quantity in an official LaWM toy optimizer step.

Purpose
-------
This deterministic diagnostic reproduces the upstream LaWM README model and
compares it with PGLT's single-change, time-scaled solver adapter.  It checks
forward losses, differentiated DEL quantities, every parameter gradient, and
parameters before and after one AdamW step.  It also probes increasing rollout
horizons to determine whether failure is caused by repeated differentiation
through the iterative solver rather than by the positive-mass or discrete
Lagrangian forward computation.

Parameters
----------
--toy-data
    Official LaWM toy tensor generated by ``examples/toy_parabolic.py``.
--output-json
    Machine-readable diagnosis destination.
--batch-size
    Number of official toy trajectories in the optimizer-step regression.
--dt
    Exact toy sampling interval.
--seed
    Torch seed used before each upstream/stable model construction.

Usage
-----
PYTHONPATH=src:third_party/LaWM python scripts/dynamics/diagnose_numerical_stability.py \
    --toy-data results/dynamics/software_validation/upstream_reference/toy_parabolic.pt \
    --output-json results/dynamics/software_validation/corrected_solver/numerical_diagnosis.json \
    --batch-size 16 --dt 0.02 --seed 0

Outputs
-------
The complete tensor statistics, first failing horizon, gradient failures, and
post-step parameter checks are saved to the requested JSON path.  No upstream
file or checkpoint is modified.
"""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path
from typing import Any, Callable

import torch

from lawm.model import LeastActionWorldModel
from lawm.train import batch_objective
from lawm.utils import load_state_tensor, make_state_weights, make_time_grid
from pglt.dynamics.lawm_adapter import StableToyLeastActionWorldModel


def parse_args() -> argparse.Namespace:
    """Parse exact toy-data and deterministic diagnostic settings."""

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--toy-data", type=Path, required=True)
    parser.add_argument("--output-json", type=Path, required=True)
    parser.add_argument("--batch-size", type=int, default=16)
    parser.add_argument("--dt", type=float, default=0.02)
    parser.add_argument("--seed", type=int, default=0)
    return parser.parse_args()


def tensor_stats(tensor: torch.Tensor) -> dict[str, Any]:
    """Summarize finite values without concealing any NaN or infinity."""

    detached = tensor.detach().float().reshape(-1)
    finite = torch.isfinite(detached)
    result: dict[str, Any] = {
        "shape": list(tensor.shape),
        "dtype": str(tensor.dtype),
        "finite_count": int(finite.sum()),
        "nonfinite_count": int((~finite).sum()),
    }
    if finite.any():
        values = detached[finite]
        result.update(
            {
                "min": float(values.min()),
                "max": float(values.max()),
                "mean": float(values.mean()),
                "norm": float(torch.linalg.vector_norm(values)),
            }
        )
    return result


def make_model(factory: Callable[..., LeastActionWorldModel], seed: int) -> LeastActionWorldModel:
    """Construct the exact README dimensions and CLI solver defaults."""

    torch.manual_seed(seed)
    return factory(
        state_dim=9,
        latent_dim=9,
        context_dim=16,
        hidden_dim=128,
        depth=3,
        solver_iters=8,
        solver_step_size=0.25,
    )


def forward_component_stats(
    model: LeastActionWorldModel, states: torch.Tensor, ts: torch.Tensor
) -> dict[str, Any]:
    """Inspect the exact positive-mass, Lagrangian, derivative, and loss path."""

    q0, q1, q2 = states[:, 0], states[:, 1], states[:, 2]
    eta = model.dynamics.infer_context(states[:, :2])
    h = ts[1] - ts[0]
    midpoint = 0.5 * (q0 + q1)
    velocity = (q1 - q0) / h
    mass = model.dynamics.lagrangian.mass_diag(midpoint, eta)
    potential = model.dynamics.lagrangian.potential(midpoint, eta)
    kinetic = 0.5 * (mass * velocity.square()).sum(dim=-1)
    discrete = model.dynamics.lagrangian.discrete_lagrangian(q0, q1, h, eta)
    residual = model.dynamics.del_residual(q0, q1, q2, h, h, eta, create_graph=True)
    output = batch_objective(
        model,
        states,
        ts,
        make_state_weights(9, states.device),
        lambda_del=1e-2,
        lambda_reg=1e-4,
    )
    return {
        "context": tensor_stats(eta),
        "midpoint": tensor_stats(midpoint),
        "velocity": tensor_stats(velocity),
        "positive_mass": tensor_stats(mass),
        "potential": tensor_stats(potential),
        "kinetic": tensor_stats(kinetic),
        "discrete_lagrangian": tensor_stats(discrete),
        "ground_truth_DEL_residual": tensor_stats(residual),
        "losses": {key: tensor_stats(output[key]) for key in ("loss", "traj", "del", "reg")},
    }


def one_step_regression(
    factory: Callable[..., LeastActionWorldModel],
    states: torch.Tensor,
    ts: torch.Tensor,
    seed: int,
) -> dict[str, Any]:
    """Check all acceptance invariants around exactly one AdamW update."""

    model = make_model(factory, seed)
    optimizer = torch.optim.AdamW(model.parameters(), lr=1e-4, weight_decay=1e-4)
    weights = make_state_weights(9, states.device)
    result: dict[str, Any] = {}
    try:
        output = batch_objective(
            model, states, ts, weights, lambda_del=1e-2, lambda_reg=1e-4
        )
        result["losses_before_backward"] = {
            key: tensor_stats(output[key]) for key in ("loss", "traj", "del", "reg")
        }
        result["all_losses_finite"] = all(
            bool(torch.isfinite(output[key]).all()) for key in ("loss", "traj", "del", "reg")
        )
        optimizer.zero_grad(set_to_none=True)
        output["loss"].backward()
        gradient_stats = {
            name: tensor_stats(parameter.grad)
            for name, parameter in model.named_parameters()
            if parameter.grad is not None
        }
        result["gradient_stats"] = gradient_stats
        result["nonfinite_gradients"] = [
            name for name, stats in gradient_stats.items() if stats["nonfinite_count"] > 0
        ]
        result["parameters_finite_before_step"] = all(
            bool(torch.isfinite(parameter).all()) for parameter in model.parameters()
        )
        optimizer.step()
        parameter_stats = {
            name: tensor_stats(parameter) for name, parameter in model.named_parameters()
        }
        result["parameter_stats_after_step"] = parameter_stats
        result["nonfinite_parameters_after_step"] = [
            name for name, stats in parameter_stats.items() if stats["nonfinite_count"] > 0
        ]
        result["passed"] = (
            result["all_losses_finite"]
            and not result["nonfinite_gradients"]
            and result["parameters_finite_before_step"]
            and not result["nonfinite_parameters_after_step"]
        )
    except Exception as error:
        result["exception"] = f"{type(error).__name__}: {error}"
        result["passed"] = False
    return result


def horizon_probe(
    factory: Callable[..., LeastActionWorldModel],
    states: torch.Tensor,
    dt: float,
    seed: int,
) -> list[dict[str, Any]]:
    """Find the earliest tested rollout length with a nonfinite total gradient."""

    records = []
    for horizon in (3, 4, 8, 16, 32, 64):
        model = make_model(factory, seed)
        subset = states[:1, :horizon]
        ts = make_time_grid(horizon, dt, subset.device)
        try:
            output = batch_objective(
                model,
                subset,
                ts,
                make_state_weights(9, subset.device),
                lambda_del=1e-2,
                lambda_reg=1e-4,
            )
            output["loss"].backward()
            nonfinite = [
                name
                for name, parameter in model.named_parameters()
                if parameter.grad is not None and not torch.isfinite(parameter.grad).all()
            ]
            records.append(
                {
                    "horizon": horizon,
                    "loss": float(output["loss"].detach()),
                    "loss_finite": math.isfinite(float(output["loss"].detach())),
                    "nonfinite_gradient_parameters": nonfinite,
                }
            )
        except Exception as error:
            records.append(
                {"horizon": horizon, "exception": f"{type(error).__name__}: {error}"}
            )
    return records


def main() -> None:
    """Run upstream and corrected solver diagnostics on the same official batch."""

    args = parse_args()
    states = load_state_tensor(args.toy_data, 9, args.batch_size)
    ts = make_time_grid(states.shape[1], args.dt, states.device)
    upstream_model = make_model(LeastActionWorldModel, args.seed)
    report = {
        "toy_data": str(args.toy_data),
        "toy_shape": list(states.shape),
        "dt": args.dt,
        "seed": args.seed,
        "upstream_solver_linearized_free_particle_jacobian_per_iteration": 1.0
        + 0.25 / args.dt,
        "stable_solver_linearized_free_particle_jacobian_per_iteration": 1.0 - 0.25,
        "forward_components_at_initialization": forward_component_stats(
            upstream_model, states, ts
        ),
        "upstream": {
            "one_step": one_step_regression(LeastActionWorldModel, states, ts, args.seed),
            "horizon_probe": horizon_probe(
                LeastActionWorldModel, states, args.dt, args.seed
            ),
        },
        "time_scaled_stable_adapter": {
            "one_step": one_step_regression(
                StableToyLeastActionWorldModel, states, ts, args.seed
            ),
            "horizon_probe": horizon_probe(
                StableToyLeastActionWorldModel, states, args.dt, args.seed
            ),
        },
    }
    args.output_json.parent.mkdir(parents=True, exist_ok=True)
    args.output_json.write_text(json.dumps(report, indent=2), encoding="utf-8")
    print(json.dumps(report, indent=2))


if __name__ == "__main__":
    main()
